### ISSUE TITLE
Couple of possible issues/doco updates

### ISSUE THREAD

**Issue by albatrossflavour** [vitorgalvao/label-colour-tag-workflow#1]
Hey,

Fantastic workflow, love it so far.

I did initially struggle to get it working and wanted to let you know what I found.

`labelcolor` was initially set to `0644`, so it wasn't able to be executed using the setup you defined.  I changed it to `0755`, and it worked.

I also had issues with the labels workflows.  I was getting the error:
`[12:43:29.382] ERROR: Label Colour Tag[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.tags.add'`

I'm an Alfred newbie, so it might be something everyone knows but wasn't evident to me.

Ended up finding out that I needed to go into the "Automation Task" under the tags workflows.  They showed that the tasks were missing.  I opened it up and selected **Update Tasks**, and it populated everything.  The label workflow now also works great.

Again, these might well be due to something I've not setup right with Alfred, but just in case others are in the same boat, though it'd be worth mentioning.  

Thanks for the workflow; I genuinely love it.

**Comment by vitorgalvao** [comment]
Hello @albatrossflavour, and thank you for the report and kind words!

> `labelcolor` was initially set to `0644`, so it wasn't able to be executed using the setup you defined. I changed it to `0755`, and it worked.

That is weird, because I’ve just verified it’s at `0744` for me and I’ve had no other reports of this. Are you per chance using [Maestral](https://maestral.app), the alternative to the Dropbox app? Maestral cannot sync file permissions because they aren't made available through the Dropbox API, which in turn can break workflows by making scripts non-executable. If that’s the case, this won’t be the only workflow affected.

As for the Automation Tasks, it will be improved in the not-too-distant future.

Thank you again. Have a great weekend.
